export const VERSIONS = [{ id: 'almeida', name: 'João Ferreira de Almeida' }]

export const BIBLE_BOOKS = [
  { id: 'gen', name: 'Gênesis', chapters: 50 },
  { id: 'exo', name: 'Êxodo', chapters: 40 },
  { id: 'lev', name: 'Levítico', chapters: 27 },
  { id: 'num', name: 'Números', chapters: 36 },
  { id: 'deu', name: 'Deuteronômio', chapters: 34 },
  { id: 'jos', name: 'Josué', chapters: 24 },
  { id: 'jdg', name: 'Juízes', chapters: 21 },
  { id: 'rut', name: 'Rute', chapters: 4 },
  { id: '1sa', name: '1 Samuel', chapters: 31 },
  { id: '2sa', name: '2 Samuel', chapters: 24 },
  { id: '1ki', name: '1 Reis', chapters: 22 },
  { id: '2ki', name: '2 Reis', chapters: 25 },
  { id: '1ch', name: '1 Crônicas', chapters: 29 },
  { id: '2ch', name: '2 Crônicas', chapters: 36 },
  { id: 'ezr', name: 'Esdras', chapters: 10 },
  { id: 'neh', name: 'Neemias', chapters: 13 },
  { id: 'est', name: 'Ester', chapters: 10 },
  { id: 'job', name: 'Jó', chapters: 42 },
  { id: 'psa', name: 'Salmos', chapters: 150 },
  { id: 'pro', name: 'Provérbios', chapters: 31 },
  { id: 'ecc', name: 'Eclesiastes', chapters: 12 },
  { id: 'sng', name: 'Cânticos', chapters: 8 },
  { id: 'isa', name: 'Isaías', chapters: 66 },
  { id: 'jer', name: 'Jeremias', chapters: 52 },
  { id: 'lam', name: 'Lamentações', chapters: 5 },
  { id: 'ezk', name: 'Ezequiel', chapters: 48 },
  { id: 'dan', name: 'Daniel', chapters: 12 },
  { id: 'hos', name: 'Oséias', chapters: 14 },
  { id: 'jol', name: 'Joel', chapters: 3 },
  { id: 'amo', name: 'Amós', chapters: 9 },
  { id: 'oba', name: 'Obadias', chapters: 1 },
  { id: 'jon', name: 'Jonas', chapters: 4 },
  { id: 'mic', name: 'Miquéias', chapters: 7 },
  { id: 'nam', name: 'Naum', chapters: 3 },
  { id: 'hab', name: 'Habacuque', chapters: 3 },
  { id: 'zep', name: 'Sofonias', chapters: 3 },
  { id: 'hag', name: 'Ageu', chapters: 2 },
  { id: 'zec', name: 'Zacarias', chapters: 14 },
  { id: 'mal', name: 'Malaquias', chapters: 4 },
  { id: 'mat', name: 'Mateus', chapters: 28 },
  { id: 'mrk', name: 'Marcos', chapters: 16 },
  { id: 'luk', name: 'Lucas', chapters: 24 },
  { id: 'jn', name: 'João', chapters: 21 },
  { id: 'act', name: 'Atos', chapters: 28 },
  { id: 'rom', name: 'Romanos', chapters: 16 },
  { id: '1co', name: '1 Coríntios', chapters: 16 },
  { id: '2co', name: '2 Coríntios', chapters: 13 },
  { id: 'gal', name: 'Gálatas', chapters: 6 },
  { id: 'eph', name: 'Efésios', chapters: 6 },
  { id: 'php', name: 'Filipenses', chapters: 4 },
  { id: 'col', name: 'Colossenses', chapters: 4 },
  { id: '1th', name: '1 Tessalonicenses', chapters: 5 },
  { id: '2th', name: '2 Tessalonicenses', chapters: 3 },
  { id: '1ti', name: '1 Timóteo', chapters: 6 },
  { id: '2ti', name: '2 Timóteo', chapters: 4 },
  { id: 'tit', name: 'Tito', chapters: 3 },
  { id: 'phm', name: 'Filemom', chapters: 1 },
  { id: 'heb', name: 'Hebreus', chapters: 13 },
  { id: 'jas', name: 'Tiago', chapters: 5 },
  { id: '1pe', name: '1 Pedro', chapters: 5 },
  { id: '2pe', name: '2 Pedro', chapters: 3 },
  { id: '1jn', name: '1 João', chapters: 5 },
  { id: '2jn', name: '2 João', chapters: 1 },
  { id: '3jn', name: '3 João', chapters: 1 },
  { id: 'jud', name: 'Judas', chapters: 1 },
  { id: 'rev', name: 'Apocalipse', chapters: 22 },
]
